#--------------------------
# My first attemts to work with Actions
#
# Copyright (c) by steppans 2022
name: Demo_run

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_test_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: Check existance of cmake
      run : cmake --version
    
    - name: Make build
      run : |
        rm -rf cmake-build/*
        cd cmake-build
        cmake ..
        make
    - name: Run hello_world_application
      run : |
        ls
        cd camke-build
        ls
